### ISSUE TITLE
Revise PropertyMap

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#10]
- Is there a better structure for it than a map with a duplicated tree? 
- Separate implementation and interface

**Comment by sgdc3** [comment]
1) what do you mean?
2)  looks interesting ;)

**Comment by ljacqu** [comment]
Regarding the first point:
If you look at the custom comparatir used in PropertyMap you'll see that it keeps a tree internally with all keys. So we have the keys in this internal tree, as well as in the Map within the PropertyMap class. 
I'm not sure if a simple Tree structure would suffice; in any case I'm convinced there's something better out there.

In contrast to this, we want to provide an interface for the second point so someone could implement another type of PropertyMap. For this, we ought to think of something more suitable than forcing a user to return Map.Entry types, for example, which is painful if you're not using a Map.
