### ISSUE TITLE
List of beans

### ISSUE THREAD

**Issue by darbyjack** [AuthMe/ConfigMe#126]
Hey there, is it possible to use a list of beans in a config option? So like, instead of having to do List<String> or just custom beans, you could do List<MyCustomBean>? 

Thanks.

**Comment by ljacqu** [comment]
> So like, instead of having to do List\<String> or just custom beans, you could do List\<MyCustomBean>

Hi, this is supported. Either as a list property within another bean itself, or if you use the property initializer (PropertyInitializer#listProperty) you can pass in a BeanPropertyType object to it.

**Comment by darbyjack** [comment]
Hey there,

Thanks for the response, I've given it a shot and I think I've almost got it. I'm trying to figure out what I'm doing wrong. I wan to make a list of a custom bean, so I'm using the listProperty method, and then I'm trying to pass in a new BeanPropertyType of the custom bean I'm using, I just can't figure out how to pass in default data (a list of the custom bean) by default.

```JAVA
public static final Property<List<GuildBuff>> TEST = PropertyInitializer.listProperty("list", new BeanPropertyType<>(GuildBuff.class, "data?"));```

**Comment by ljacqu** [comment]
You can define the default entries of the List either by supplying a List (1) or by providing them to the varargs method one the builder (2):

(1)
```java
        PropertyInitializer.listProperty(BeanPropertyType.of(WorldGroupConfig.class))
            .path("list")
            .defaultValue(Arrays.asList(new WorldGroupConfig("world"), new WorldGroupConfig("nether")))
            .build();
```

(2)
```java
        PropertyInitializer.listProperty(BeanPropertyType.of(WorldGroupConfig.class))
            .path("list")
            .defaultValue(new WorldGroupConfig("world"), new WorldGroupConfig("nether"))
            .build();
```

Variant 1 works out well if you have complex defaults you can't just create on the spot. Then you could move the creation of the default to a static method and call it inside the builder:
```java
        PropertyInitializer.listProperty(BeanPropertyType.of(WorldGroupConfig.class))
            .path("list")
            .defaultValue(createDefaultWorlds())
            .build();

   private static List<WorldGroupConfig> createDefaultWorlds() {
     WorldGroupConfig conf1 = new WorldGroupConfig("nether");
     conf1.setFoo(true);
     conf1.setBar(0);
     return Arrays.asList(conf1);
   }
```

**Comment by darbyjack** [comment]
Thank you so much! This helped a ton.
