### ISSUE TITLE
Allow private fields as properties

### ISSUE THREAD

**Issue by Sxtanna** [AuthMe/ConfigMe#133]
Allowing for private fields would make usage from Kotlin less ugly.

In its current state, the library resolves all fields, private included, and just throws away fields that are inaccessible.

Simply inserting `Field#setAccessible(true)` above this line here:
https://github.com/AuthMe/ConfigMe/blob/1084f4311358410c4a80eaaa619c52927ffcd84c/src/main/java/ch/jalu/configme/configurationdata/ConfigurationDataBuilder.java#L115

Will resolve this issue.

**Comment by ljacqu** [comment]
I don't have much experience with Kotlin—are there any other shortcomings that could be improved for Kotlin integration? I'd like to get a better picture as to maybe bundle a few improvements to facilitate usage from Kotlin.

**Comment by Sxtanna** [comment]
Aside from that, a benefit not only for Kotlin, but Java as well would be for the project to utilize the jetbrains annotations to mark nullability and contracts.

IntelliJ is able to infer some of them, but proper definition is always better.

**Comment by ljacqu** [comment]
As long as the field is static, it will be picked up by the default configuration data builder. Sample Kotlin code that will work with the next release:
```kotlin
import ch.jalu.configme.Comment
import ch.jalu.configme.SettingsHolder
import ch.jalu.configme.SettingsManagerBuilder
import ch.jalu.configme.properties.PropertyInitializer
import ch.jalu.configme.utils.Utils
import java.nio.file.Paths

fun main(args: Array<String>) {
    val path = Paths.get("./configme-kt-test.yml")
    Utils.createFileIfNotExists(path);

    val settings = SettingsManagerBuilder
        .withYamlFile(path)
        .configurationData(TitleSettings.javaClass)
        .create()

    println("App: ${settings.getProperty(TitleSettings.TITLE_TEXT)}")
}

object TitleSettings: SettingsHolder {

    @Comment("Demo")
    val TITLE_TEXT = PropertyInitializer.newProperty("title.text", "woof")

}
```

Previously, `@JvmField` was required.
