### ISSUE TITLE
Create FloatProperty

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#268]
Just like DoubleProperty, we should offer a FloatProperty.

- Introduce FloatProperty
- Check if other basic types would be useful

**Comment by zrdzn** [comment]
> Just like DoubleProperty, we should offer a FloatProperty.
> 
> * Introduce FloatProperty
> * Check if other basic types would be useful
ShortProperty and LongProperty are also missing. These objects can be easily added because their primitive fields already exist in the PrimitivePropertyType class. I can pr this issue if it's not already in the works.

**Comment by ljacqu** [comment]
Long would definitely also be interesting. Short is fine by me. I probably wouldn‘t do char or byte though.
If you have time & interest, a PR would be greatly appreciated! :smile:

**Comment by zrdzn** [comment]
#269
