### ISSUE TITLE
Throw if @Comment and registerComments use the same path for a comment

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#342]
Currently, if `@Comment` on a property and some statement in `SettingsHolder#registerComments` set the comments for the same path, one of the comments is just discarded. This is misleading, and should be prevented by throwing an exception. There's no use case to defining part of the comment in the annotation or in the method—one approach should be used per path. 

## To do
- Change `CommentsConfiguration` to throw an exception if a comment is registered to a path that already has comments
- Add unit tests

## Hint
- Map#put returns the old value for the same key if it existed, i.e. if it's not null, a comment already existed!

**Comment by sharief007** [comment]
We can use `Map#containsKey` to check if the path is already mapped to a list of comments before throwing the exception. However, this approach may not allow us to overwrite an existing path.
It seems the `CommentsConfiguration#setComment` should allow overriding the paths. Hence as mentioned in the issue description `Map#put` is used to check.

Pull Request: https://github.com/AuthMe/ConfigMe/pull/373
