### ISSUE TITLE
Revise argument order in Property classes

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#364]
The order of the arguments is not consistent across Property implementations. ConfigMe 2.0 would be a nice opportunity to align this again.

Current constructors:
- `BeanProperty(Class<T> beanType, String path, T defaultValue)`
- `ListProperty(String path, PropertyType<T> type, T... defaultValue)` <- this is the desired order
- `MapProperty(String path, Map<String, V> defaultValue, PropertyType<V> type)`

Desired outcome:
- path as first parameter
- type as second (e.g. PropertyType, or Class<?> giving context)
- default value last

## To do
- Go through `Property` extensions and ensure that the constructor parameters are in the order `String path, PropertyType type, Object defaultValue`. Fix any infractions.
- Note that the arguments of the methods in `PropertyInitializer` shouldn't be changed. Some methods like `newBeanProperty` don't adhere to the desired order, but the arguments are consistent within the class, so there's no need for an unnecessary breaking change there.

**Comment by yagahut** [comment]
@ljacqu Hey, just have submitted pr, take a look #385
