### ISSUE TITLE
Refactor RegexProperty to use a property type (create RegexType)

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#368]
RegexProperty implements conversions in the class and not via a property type. In a move to make type behavior more reusable, we want to model type conversions as often as possible as a PropertyType for reusability.

## To do
- Create `RegexType` (extends from `PropertyAndLeafType`)
- Move conversion logic from the RegexProperty to the new type
- Change RegexProperty to extend TypeBasedProperty and to use the RegexType
- Add RegexType to the list of default types in the leaf value handler -> LeafValueHandlerImpl#createDefaultLeafTypes

**Comment by sharief007** [comment]
Pull Request: https://github.com/AuthMe/ConfigMe/pull/371
