### ISSUE TITLE
Case-insensitive pattern type

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#378]
Extend RegexType to have a second instance out of the box that is a case-insensitive pattern. See how `StringType` does it similarly for the lowercase String.

## To do
- Extract the pattern compilation into a separated protected method (similar to `StringType#transformToString`)
- Add a second constant to RegexType that will create a pattern with `Pattern.compile(string, Pattern.CASE_INSENSITIVE)`
- Extend tests

**Comment by shirsho-roy** [comment]
@ljacqu I would like to work on this issue. Please assign it to me

**Comment by ljacqu** [comment]
Hi @shirsho-roy , looks like sharief beat you to it 😅 Please see any other [good-first-issue](https://github.com/AuthMe/ConfigMe/issues?q=is%3Aopen+label%3Agood-first-issue+sort%3Aupdated-desc) labels if anything catches your fancy! Thanks
