### ISSUE TITLE
Add BigDecimal inline array property type

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#380]
Can only be done when #230 is closed: introduce an inline array property type constant for the type `BigDecimal`. It should behave like the other number types.

## To do
- Add a BIG_DECIMAL constant for the BigDecimal number type (between Double and String)
- Adapt tests

**Comment by Akshayp02** [comment]
hey! 
i would like to contribute on this issue can you assign me to explore more in it.🙂

**Comment by ljacqu** [comment]
Will do! Just please note this cannot be started before the linked issue is done. I will comment again when this can be picked up (should be in 1-2 days)

**Comment by Akshayp02** [comment]
Thank you for letting me know. I completely understand, and I'm happy to wait until the linked issue is resolved. Please take your time to address it, and once it's done, I'll be ready to pick up this task. Feel free to reach out when you're ready for me to proceed, and I'll be happy to contribute. Looking forward to it!

**Comment by ljacqu** [comment]
hi @Akshayp02, thanks for your patience! The relevant code changes are now available on master, meaning that this is not blocked anymore. The starting point for this issue is `InlineArrayPropertyType`.

**Comment by Akshayp02** [comment]
Hello @ljacqu 😊 thanks for the reply. 
Ok mam I'll start working on this issue.

**Comment by Akshayp02** [comment]
Mam I'm a little bit confused about where I've to make changes I mean in a particular file, directory of I've to create a new file for it .

**Comment by Akshayp02** [comment]
Hello Mam

I hope you're doing well. I'm currently working on the project and have some questions about a specific task. I'm a bit confused about which file I should be working on for this task. Could you please provide a brief description or guidance on where I should focus my efforts?

Thank you for your assistance.

**Comment by ljacqu** [comment]
Hi, essentially the `InlineArrayPropertyType` offers a property type for various types, but it's missing an implementation for BigDecimal. So the same way there is an inline array property type for double or String, we'd want one for the BigDecimal type there. This task entails adding that and extending the tests in InlineArrayPropertyTypeTest so that the new BigDecimal type is also covered.

**Comment by FdHerrera** [comment]
Hey guys

Just created [this PR](https://github.com/AuthMe/ConfigMe/pull/399) to address this issue.
Let me know if it looks good to you.

Thank you in advance!
