### ISSUE TITLE
Multiple-line string not supported

### ISSUE THREAD

**Issue by gamerover98** [AuthMe/ConfigMe#405]
### What I'm trying to do
I'm attempting to include a JSON schema in a YAML property. 
Here's an example:

```YAML
json: |
  {
    "age": 30,
    "city": "Rome",
    "email": "john.doe@example.com"
  }
```
### The issue
While ConfigMe reads this property correctly, it saves the config file with the JSON schema replaced by a string:

```YAML
json: "{\n  \"age\": 30,\n  \"city\": \"Rome\",\n  \"email\": \"john.doe@example.com\"\   \n}\n"
```

### What I'm expected
I expect ConfigMe to load the JSON schema without replacing it with a string.

## My test code
```JAVA
@Test
void test() throws IOException {
    // given
    Path configFile = TestUtils.copyFileFromResources("/config/example_json_property.yml", temporaryFolder);
    PropertyResource resource = new YamlFileResource(configFile);

    Property<String> jsonProperty = PropertyInitializer.newProperty("json", "");
    ConfigurationData configurationData = createConfiguration(singletonList(jsonProperty));
    configurationData.initializeValues(resource.createReader());

    // when
    resource.exportProperties(configurationData);

    // then
    String json = jsonProperty.determineValue(resource.createReader()).getValue();
    Person person = JsonUtil.parseConfig(json, Person.class);
    ...
}
```

Perhaps we should create and use a `JsonProperty` class instead of a `StringProperty` class.

**Comment by ljacqu** [comment]
I don't really understand your point. Your starting configuration is the same value as what ConfigMe ends up exporting, just written in different formats. In YAML, the following are exactly the same values:
```yaml
json: |
  {
    "age": 30,
    "city": "Rome",
    "email": "john.doe@example.com"
  }
```
```yaml
json: "{\n  \"age\": 30,\n  \"city\": \"Rome\",\n  \"email\": \"john.doe@example.com\"\   \n}\n"
```

Both YAML blocks will be read the same way by ConfigMe. We could come up with a way to define how string should be exported, as separate property type or as an option on String, which I'm sure would be useful for a wide array of applications.
As for JSON-specific things, I don't think it makes much sense to have features out of the box in ConfigMe to mix JSON into YAML.
