### ISSUE TITLE
Revise structure

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/ConfigMe#56]
For version 1.0 a lot of the new components will be rewritten, including bringing on breaking changes. The behavior of the built-in properties and of the default YAML reader should remain the same, however.

Basically the first step is to create interfaces with an improved structure design and then to pick out all the good stuff from the current implementation and to reimplement whatever is putting us into serious technical debt.

Technically speaking one of the main goals is to avoid all of those `instanceof` checks we have throughout the code. It should suffice to use the interface methods themselves without knowing anything about the property implementation.

In order to achieve this it's important to define the "responsibilities" that each interface has. The PropertyResource is basically a convenience layer above SnakeYAML (in the YAML case); it allows to fetch paths easily in a type-safe manner and handles writing YAML including comments (which SnakeYAML doesn't support).

The Property interface, using the PropertyResource, determines what value it should have (something it converts from the property resource, or a default value if that result was unfit). What's new is that it will also convert its actual value to an "export type", which should just be basic Java types like String / int / ... and lists thereof. This is a big change and will allow us to avoid making checks for the concrete Property implementation in the property resources.

Another issue we struggle with is that currently if a new value is set for the property it will be set on the property resource. So the property resource is juggling with "basic types" it read from a YAML file but also with complex types that may be set for the property. In other words, each Property implementation needs to be aware that either the resource will return an already finished value, or it has to construct it (think of EnumProperty that gets Strings from the resource but also gets an Object to check if it's already an enum entry of its type).

To fix this we need to split reading from the resource and then managing the values -> PropertyResource now has a method returning a PropertyReader (names subject to change) and this reader will only be used initially to determine the property's values. Those evaluated values will, however, be managed elsewhere (in a ValuesRegistry?) for further use, and the reader will be discarded after that initial read.

----

A lot of these issues arose because I didn't want to do anything YAML-specific in Property itself, so basically it never dealt with how its value gets exported at all. This means that each Property that has some special behavior had to be handled in the YamlResource itself with specific `instanceof` checks, which doesn't make it extendable well.

I still think it's a nice feat to keep the specific format separate from Property, but Property should definitely be the one to define its value's representation in the export. This is where a new method on Property comes into play that will return only basic types (String / int / double / boolean / ..?, and lists thereof, and probably Map&lt;String, basic types>). We'll just have to assume that whatever we decide are "basic types" will have to be handled properly by the property resource.

**Comment by Gnat008** [comment]
This sounds exciting. I can't wait to see how this progresses!

Is it too soon yet to know what changes might be breaking?

**Comment by ljacqu** [comment]
Heya @Gnat008 thanks for the comment :blush: 
As a user you typically only interact with SettingsManager, Property and MigrationService and while some methods might change on there, it won't be anything fundamental :) As mentioned the behavior of the YAML reader that comes with it also shouldn't change. 

The branch [new-structure](https://github.com/AuthMe/ConfigMe/compare/master...new-structure) has some initial sketches. I'm very thankful for any input you might have (challenging the interfaces or the naming, etc.)

**Comment by Gnat008** [comment]
Those upsides seem to outweigh the downside listed there. How much of a concern is the added method call to get the `PropertyType` every time?

Passing in the path every time would be annoying, true... I wonder if there is a better way to handle that. Storing the path in the implementing objects would work, but then that's another added thing, and does it really make sense for it to keep track of that?

**Comment by ljacqu** [comment]
Hi @Gnat008 thanks for the feedback, I really appreciate it! I agree with you and will do the split. I've just encountered some issues again with OptionalProperty that would definitely work out much better with separate type handling. I'll try to go without binding the path to those types for now. You're right that it shouldn't be a big hassle :smile:

**Comment by ljacqu** [comment]
Update: the bean mapper is causing trouble and I haven‘t been able to reuse the property types xP So I‘ve been putting off development because it just raises tons of problems

**Comment by ljacqu** [comment]
I was hoping to be done at this point but still some work to be done. Plan for the next days is to clean up a little and have the new structure on master. In Sep I‘ll pick it back ip and finish the 1.0 version

**Comment by ljacqu** [comment]
Not yet fully exhaustive but a migration guide is being prepared at https://github.com/AuthMe/ConfigMe/wiki/Migrating-from-0.x-to-1.x

For now I close this issue as I'm not sure what there would still be to do in a very general sense.
