### ISSUE TITLE
Anything special for UTF-8?

### ISSUE THREAD

**Issue by darbyjack** [AuthMe/ConfigMe#84]
Hey there,

You said to use GitHub for questions since you see it faster. Do I have to do anything special to make sure the config is loading as UTF-8? I'm getting reports from some Chinese players that it's not working properly because it doesn't handle the Unicode properly.

Cheers,
Glare.

**Comment by ljacqu** [comment]
Hi Glare,

This is the perfect place—also for questions :) ConfigMe uses UTF-8 by default, unless you've specifically set something else when creating the YamlFileResource. What's possible is that your Chinese user has actually saved the file in a different encoding. 
Do you perhaps have an error or a sample of the file?
