### ISSUE TITLE
Splitting up the config?

### ISSUE THREAD

**Issue by darbyjack** [AuthMe/ConfigMe#85]
Hey there,

Is it possible to take an already generated config and split it up into files? For example, I have multiple parts currently in my config but I want to clean it up so I figure I could split each section into its own file. I know for new configs being generated it'll be like this automatically, but is there a way to take the already generated ones where people have modified stuff from the default and move that to the new configs?

Thanks,
Glare.

**Comment by ljacqu** [comment]
hi @darbyjack, I guess the best way would be to implement your own custom migration service with that behavior: https://github.com/AuthMe/ConfigMe/blob/master/src/main/java/ch/jalu/configme/migration/PlainMigrationService.java The migration service is set when the settings manager is initialized, so I'd add it to your main one, I guess, making sure that the other aren't initialized until the migration has been performed.

**Comment by darbyjack** [comment]
Hey,

Thanks for getting back to me. While I have you, is there a way to handle comments like the config keys? I want to be able to add new comments in on comments configuration section (so like at the top of a section) and have the config pick it up. Is this possible?

Thanks,
Glare.

**Comment by ljacqu** [comment]
The SettingsHolder interface offers a method to register comments at arbitrary paths (including root, which would be empty string, or any parent sections).

**Comment by darbyjack** [comment]
Correct, but what if you have a version you release with a single line comment and you want to add another line for the next update? If I tested it correctly it would not add it in.

**Comment by ljacqu** [comment]
As soon as the configuration is rewritten (say, because a property is missing) then it will updated all comments to the state that it was configured to. It won't keep any old comments in that sense, just do whatever the SettingsHolder classes are telling it to.

**Comment by darbyjack** [comment]
Hey, thanks for the response. The last question, is there a way to tell the config to delete stuff? I'm doing a refractor of a module in my plugin and I want to rewrite that part of the plugin.

**Comment by ljacqu** [comment]
Also through the  migration service :) If a certain path exists (checked on the file readerer), return true from the method and it will retrigger a rewrite.
